# Serviceリソースの定義
apiVersion: v1
kind: Service
metadata:
  # サービスに付与するラベル
  labels:
    app: my-service
  # サービスの名前
  name: my-service
spec:
  # このサービスが対象とするPodのセレクター
  selector:
    app: my-deployment
  # ポート設定
  ports:
  - protocol: TCP
    # サービスが公開するポート
    port: 80
    # Podがリッスンするポート
    targetPort: 80
  # サービスタイプ（ClusterIPはクラスター内部からのみアクセス可能）
  type: ClusterIP
